export const THEMES = [
  {
    id: 'dinosaurs',
    emoji: '🦕',
    label: 'Dinosaurs',
    desc: 'Jurassic adventures',
    color: '#22c55e',
    scenes: [
      'flying on the back of a friendly pterodactyl soaring over a prehistoric jungle with volcanoes erupting in the background',
      'riding a giant T-Rex through a lush prehistoric forest, holding on to a saddle, looking excited',
      'discovering a massive dinosaur egg nest with baby dinosaurs hatching all around',
      'sliding down the long neck of a friendly Brachiosaurus like a slide, laughing with joy',
      'racing alongside a Triceratops through a field of giant prehistoric ferns',
      'sitting beside a baby Raptor in a cozy fern cave, the two of them becoming friends',
      'escaping a playful Spinosaurus by crossing a log bridge over a rushing river',
      'watching a meteor shower from the back of a sleeping diplodocus under the stars',
    ],
  },
  {
    id: 'safari',
    emoji: '🦁',
    label: 'Safari',
    desc: 'Wild African plains',
    color: '#f59e0b',
    scenes: [
      'riding a majestic lion across the African savanna at golden sunset, mane flowing in the wind',
      'racing an ostrich across the open plains, both running at full speed',
      'feeding a very tall giraffe leaves from the treetops at a watering hole',
      'splashing and playing with a family of baby elephants in a muddy watering hole',
      'riding on the back of a zebra through a herd of zebras at sunrise',
      'camping under a giant acacia tree surrounded by curious meerkats and fireflies at night',
      'watching rhinos from the basket of a colorful hot air balloon floating above the savanna',
      'swimming safely alongside happy hippopotamuses in a wide African river',
    ],
  },
  {
    id: 'space',
    emoji: '🚀',
    label: 'Space',
    desc: 'Galaxies & planets',
    color: '#8b5cf6',
    scenes: [
      'piloting a rocket ship through the rings of Saturn, stars and nebulas all around',
      'bouncing in low gravity on the surface of the Moon, Earth visible in the background',
      'meeting a friendly smiling alien on the red rocky surface of Mars, shaking hands',
      'doing a spacewalk outside a space station, tethered with Earth glowing below',
      'planting a flag on a brand new glowing planet never discovered before',
      'zooming through an asteroid field in a jetpack suit, dodging space rocks',
      'landing a small rocket on the surface of a giant comet made of ice and glowing dust',
      'floating weightlessly through a colorful galaxy full of stars and swirling nebulas',
    ],
  },
  {
    id: 'ocean',
    emoji: '🐬',
    label: 'Ocean',
    desc: 'Deep sea wonders',
    color: '#06b6d4',
    scenes: [
      'riding a leaping dolphin through ocean waves at sunset, holding on and laughing',
      'swimming alongside a gentle whale shark through colorful coral reefs',
      'discovering a glowing treasure chest on the ocean floor with a friendly octopus as a guide',
      'racing a sea turtle through a kelp forest, both swimming as fast as they can',
      'exploring a magical underwater city built into a coral reef, fish swimming everywhere',
      'surfing a giant wave on a surfboard, seagulls flying overhead',
      'befriending a giant friendly sea serpent who is curling around playfully',
      'discovering a glowing underwater volcano with colorful fish darting around it',
    ],
  },
  {
    id: 'superheroes',
    emoji: '⚡',
    label: 'Superheroes',
    desc: 'Saving the world',
    color: '#ef4444',
    scenes: [
      'flying high above a glittering city skyline at dawn wearing a superhero cape',
      'heroically stopping a runaway train on a tall bridge by holding it back with both hands',
      'battling a giant friendly robot in the middle of the city, surrounded by cheering people',
      'using a superpower to catch a kitten falling from a crumbling skyscraper',
      'racing The Flash in a lightning-fast sprint through a dramatic canyon landscape',
      'standing on a podium receiving a giant gold medal from a cheering crowd',
      'deflecting a meteor with an energy force field while floating in outer space',
      'leading a team of superhero friends into an exciting adventure',
    ],
  },
  {
    id: 'magic',
    emoji: '🧙',
    label: 'Magic',
    desc: 'Wizards & dragons',
    color: '#ec4899',
    scenes: [
      'riding a friendly dragon through the sky above a glowing enchanted castle at twilight',
      'casting colorful spells from the top of an ancient wizard tower, stars swirling around',
      'stepping through a magical glowing portal that leads to a fairy kingdom',
      'racing other young wizards on enchanted broomsticks through the clouds at night',
      'discovering a tiny baby phoenix hatching in a magical nest of golden fire',
      'pulling a legendary glowing sword from a stone in an enchanted forest clearing',
      'brewing a bubbling magical potion surrounded by forest animals and mushrooms',
      'flying on a magic carpet over a colorful bazaar with glittering lights below',
    ],
  },
  {
    id: 'pirates',
    emoji: '☠️',
    label: 'Pirates',
    desc: 'Treasure & adventure',
    color: '#78716c',
    scenes: [
      'steering a magnificent pirate galleon through a dramatic ocean storm, waves crashing',
      'sword fighting on the deck of a ship with a friendly rival pirate, both laughing',
      'digging up a treasure chest full of gold coins on a tropical desert island',
      'navigating by stars on a calm ocean night from the crow\'s nest of a tall ship',
      'befriending a giant friendly sea kraken who has wrapped a tentacle around the ship gently',
      'swinging on a rope from the crow\'s nest across to another ship, fearlessly smiling',
      'building a raft to escape a deserted tropical island while parrots watch',
      'trading treasure at a busy colorful pirate port marketplace',
    ],
  },
  {
    id: 'sports',
    emoji: '🏆',
    label: 'Sports',
    desc: 'Champion moments',
    color: '#10b981',
    scenes: [
      'scoring the championship winning goal in a packed soccer stadium, crowd going wild',
      'slam dunking a basketball in the NBA finals, confetti falling from the ceiling',
      'crossing the marathon finish line in first place, arms raised in victory',
      'catching the game-winning touchdown in the end zone, leaping dramatically',
      'landing a perfect trick at a skateboarding competition, judges holding up perfect-score cards',
      'standing on the Olympic gold medal podium, receiving a medal with a huge crowd cheering',
      'hitting a grand slam home run out of the park, rounding the bases triumphantly',
      'sticking a perfect landing after a gymnastics routine, judges and crowd on their feet',
    ],
  },
];

export const COMPLEXITIES = [
  {
    id: 'simple',
    label: 'Simple',
    age: 'Ages 3–5',
    desc: 'Big bold shapes, minimal background detail',
    promptModifier: 'very simple design with large bold outlines and minimal background detail, suitable for very young children',
  },
  {
    id: 'medium',
    label: 'Medium',
    age: 'Ages 6–9',
    desc: 'Balanced detail with fun backgrounds',
    promptModifier: 'moderate detail with clear outlines and a fun detailed background, suitable for children aged 6-9',
  },
  {
    id: 'detailed',
    label: 'Detailed',
    age: 'Ages 10+',
    desc: 'Rich scenes packed with coloring zones',
    promptModifier: 'rich detail with intricate background elements and many distinct regions to color, suitable for older children and adults',
  },
];

export const PAGE_COUNTS = [4, 6, 8, 12];
